// Type declarations for @liquicode/jsonstor-sqlite
//
// Generated by jsonstor-docs/build/build-adapter-docs.js from docs/data/adapters.js.
// Edits here are erased by the next build.
//
// Documents are stored in a Sqlite3 file.

declare module '@liquicode/jsonstor-sqlite'
{

	//---------------------------------------------------------------------
	// A column this adapter is allowed to create.
	//
	// Used only while the adapter is creating the table. Afterwards the table itself is
	// the authority on what its columns are.

	export interface ColumnDefinition
	{
		Name: string;
		/** The SQL type. A missing or non-string value takes the adapter's default. */
		Type?: string;
		/** True for the column which carries the document identifier. */
		Key?: boolean;
	}


	//---------------------------------------------------------------------
	// The settings this adapter takes.

	export interface AdapterSettings
	{
		/** Path to the Sqlite database file. Pass `":memory:"` for a database which lives only as long as the storage does. */
		Path: string;
		/** The name of the table to use. */
		Table: string;
		/** The column to treat as the document identifier. Empty discovers it from the table: a column named `_id`, then an auto-increment key. `IdField` is the former spelling and still works. Defaults to `""`. */
		PrimaryKey?: string;
		/** Allow an update or a replacement to change the identifier. Off by default, so an operation which would move it is refused by name rather than silently discarded. Defaults to `false`. */
		PrimaryKeyMutable?: boolean;
		/** Allow the adapter to create the table and the columns it is told to create. It never adds a column because a document had a field. Defaults to `false`. */
		ModifySchema?: boolean;
		/** The column which stores the document as JSON text. Empty means none, and then every field must already be a column. Created when missing if `ModifySchema` is `true`. Defaults to `""`. */
		PayloadColumn?: string;
		/** Store the whole document in the payload, making the other columns an index over it. When `false` the payload holds only the fields which have no column. Defaults to `false`. */
		PayloadSync?: boolean;
		/** Columns to create, as `{ Name, Type, Key }`. Used only when this adapter creates the table; afterwards the table itself is the authority. Defaults to `[]`. */
		Columns?: ColumnDefinition[];
	}


	//---------------------------------------------------------------------
	// The storage this adapter returns.
	//
	// Its members belong to jsonstor rather than to any adapter, so they are left open
	// here rather than restated - an adapter which described them would be describing
	// the storage interface, which is not its to describe.

	export interface Storage
	{
		[ MemberName: string ]: any;
	}


	//---------------------------------------------------------------------
	// The adapter itself. This is what `require()` returns, and what you hand to
	// `jsonstor.LoadPlugin()`.

	export interface StorageAdapter
	{
		/** Always `'jsonstor-sqlite'`. The name this adapter registers under. */
		AdapterName: string;
		AdapterDescription: string;
		GetAdapter( jsonstor: any, Settings: AdapterSettings ): Storage;
	}


	//---------------------------------------------------------------------
	// The default export is the adapter, and is what `require()` returns.

	const adapter: StorageAdapter;
	export default adapter;


	//---------------------------------------------------------------------
	// Named exports, matching src/jsonstor-sqlite.mjs one for one.

	export const AdapterName: string;
	export const AdapterDescription: string;
	export const GetAdapter: StorageAdapter[ 'GetAdapter' ];

}
