// @liquicode/jsonstor-sqlite - ESM entry point.
//
// Generated by jsonstor-docs/build/build-adapter-docs.js from docs/data/adapters.js.
// Edits here are erased by the next build.
//
// This wrapper exists so that `import { GetAdapter } from '@liquicode/jsonstor-sqlite'` works.
// Without it Node reports `Named export 'GetAdapter' not found`: the adapter assigns a
// whole object literal to `module.exports`, and `cjs-module-lexer` reads only
// `exports.<name> =` assignments.
//
// ***This is a wrapper and never a second build.*** It imports the CommonJS module and
// re-exports what is already there, so `require()` and `import` reach one adapter.

import ADAPTER from './jsonstor-sqlite.js';


//---------------------------------------------------------------------
// The adapter itself.
// Same object as `require( '@liquicode/jsonstor-sqlite' )` returns.

export default ADAPTER;


//---------------------------------------------------------------------
// The adapter's three members.

export const AdapterName = ADAPTER.AdapterName;
export const AdapterDescription = ADAPTER.AdapterDescription;
export const GetAdapter = ADAPTER.GetAdapter;
